### 1. Base health check
GET http://127.0.0.1:8000/
Accept: application/json

###

### 2. Optional hello route (if implemented as /hello/{name})
GET http://127.0.0.1:8000/hello/User
Accept: application/json

###


POST http://127.0.0.1:8000/exe/analizar-json
Content-Type: application/json
Accept: application/json

{
  "input_folder": "./results/20251213_171417_sim_ST0_S0.57_WC0.29_D15",
  "output_folder": "./results/20251213_171417_sim_ST0_S0.57_WC0.29_D15",
  "seleccion_agregacion": "1",

  "delta_media": 60,
  "delta_acumulada": null,

  "graf_barras_est_med": null,
  "graf_barras_est_acum": null,
  "graf_barras_dia": null,
  "graf_linea_comp_est": null,
  "graf_linea_comp_mats": null,

  "mapa_densidad": null,
  "video_densidad": null,
  "mapa_voronoi": null,
  "mapa_circulo": "10",
  "mapa_desplazamientos": null,

  "filtrado_EstValor": null,
  "filtrado_EstValorDias": null,
  "filtrado_Horas": null,
  "filtrado_PorcentajeEstaciones": null
}

